version: "3"
services:
  cloudflare-ddns:
    container_name: cloudflareDNS
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      PUID: 0
      PGID: 0
      API_KEY: ktez6xlMnDf0yaD5xGuUjgI-PV95A2Dn3tohz6wV
      ZONE: cityplug.co.uk
      SUBDOMAIN: dev.cityplug.co.uk

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /relay/.AppData/portainer/data:/data
    ports:
      - 9000:9000

  portainer:
    container_name: portainer_agent
    image: portainer/agent:2.11.1
    restart: always
    ports:
      - "9001:9001"
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /relay/.AppData/portainer:/data
    
  ubuntu:
    build: .
    container_name: ubuntu
    restart: always
